jobs:
  - template: azure-pipelines-template.yml
    parameters:
      IMAGE: [windows-latest, ubuntu-latest]
      RELEASE: [R2021a, R2021b, R2022a, R2022b, R2023a, R2023b, R2024a, R2024b, R2025a, R2025b, R2026a, latest, latest-including-prerelease]
  - template: azure-pipelines-template.yml # R2026a no longer supports Intel Macs but Azure does not yet have ARM Macs
    parameters:
      IMAGE: [macOS-latest]
      RELEASE: [R2021a, R2021b, R2022a, R2022b, R2023a, R2023b, R2024a, R2024b, R2025a, R2025b]
