package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        step {
            id = "matlabTestRunner"
            type = "matlabTestRunner"
            param("logLoggingLevel", "Default")
            param("pdfTestArtifact", "results/testResult.pdf")
            param("sourceFolders", "code")
            param("filterTestFolderByName", "tests")
            param("logOutputDetail", "Default")
            param("MatlabRoot", """C:\Program Files\MATLAB\R2024a""")
        }
    }
    steps {
        insert(1) {
            step {
                id = "matlabCommandRunner"
                type = "matlabCommandRunner"
                param("matlabCommand", "pwd")
                param("MatlabPathKey", """C:\Program Files\MATLAB\R2023b""")
            }
        }
    }
}
